<!DOCTYPE html>
<html lang="en">
<head>
  <title>Form Example using jQuery/Rest API for better user experience</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="/js/jquery-validation.js"></script>
  <script type="text/javascript" src="/js/validate.js"></script>
  <script type="text/javascript" src="/js/formhelp.js"></script>
</head>
<body>

<style>
.error {
  color: red;
  font-weight: normal;
}
</style>



<div class="container">
      <h2>Loan Application</h2>
  <form id='loan_form' action="/loan/submit" method="post">
      <div class="row">
          <div class="col-md-6 form-group">
              <label for="fname">First Name:</label>
              <input type="text" class="form-control" id="fname" placeholder="Enter first name" name="fname">
          </div>  
          <div class="col-md-6 form-group">
              <label for="lname">Last Name:</label>
              <input type="text" class="form-control" id="lname" placeholder="Enter last name" name="lname">
          </div>
          <div class="col-md-6 form-group">
              <label for="email">Email:</label>
              <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
          </div>
          <div class="col-md-6 form-group">
              <label for="phone">Phone</label>
              <input type="text" class="form-control" id="phone" placeholder="Enter phone" name="phone">
          </div>
          <div class="col-md-6 form-group">
              <label for="zip">Zip:</label>
              <input type="text" class="form-control" id="zip" placeholder="Enter zip" name="zip" onBlur='getCityStateByZip($("#zip").val())'>
          </div>
          <div class="col-md-6 form-group">
              <label for="street">Street Address:</label>
              <input type="text" class="form-control" id="street" placeholder="Enter street" name="street">
          </div>
          <div class="col-md-6 form-group">
              <label for="city">City:</label>
              <input type="text" class="form-control" id="city" placeholder="Enter city" name="city">
          </div>
          <div class="col-md-6 form-group">
              <label for="state">State:</label>
              <input type="text" class="form-control" id="state" placeholder="Enter state" name="state">
          </div>
          <div class="col-md-6 form-group">
              <label for="routing">Bank Routing #:</label>
              <input type="text" class="form-control" id="routing" placeholder="Enter routing number" name="routing"  onBlur='getBankByRouting($("#routing").val())'>
          </div>
          <div class="col-md-6 form-group">
              <label for="bank_name">Bank Name:</label>
              <input type="text" class="form-control" id="bank_name" placeholder="Enter bank_name" name="bank_name">
          </div>
          <div class="col-md-6 form-group">
              <button type="submit" class="btn btn-default">Submit</button>
          </div>
    </div>
  </form>
</div>

</body>
</html>
