<!DOCTYPE html>
<html lang="en">
<head>
  <title>Form Example using jQuery/Rest API for better user experience</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="/js/jquery-validation.js"></script>
  <script type="text/javascript" src="/js/validate.js"></script>
  <script type="text/javascript" src="/js/formhelp.js"></script>
</head>
<body>

<style>
.error {
  color: red;
  font-weight: normal;
}
</style>



<div class="container">
<br><br>
      <center><h4>Thank you for your loan application</h4></center>
</div>

</body>
</html>
